### ISSUE TITLE
parallel-enabled hdf5 library fails the package compilation

### ISSUE THREAD

**Issue by mikejiang** [RGLab/ncdfFlow#35]
``` bash
In file included from /usr/include/hdf5.h:24:0,
                 from hdfFlow.h:4,
                 from hdfFlow.c:1:
/usr/include/H5public.h:63:20: fatal error: mpi.h: No such file or directory
 #   include <mpi.h>
                    ^
```

This occurred on `rhino` servers since IT updated the system last time. Apparently `hdf5` was built with the option:

``` bash
./configure --enable-parallel
```

And it sets the flag `H5_HAVE_PARALLEL` in `/usr/include/H5pubconf.h`

``` c
#define H5_HAVE_PARALLEL 1
```

which causes `mpi.h` to be included  in `/usr/include/H5public.h` 

``` c
#ifdef H5_HAVE_PARALLEL
#   define MPICH_SKIP_MPICXX 1
#   define OMPI_SKIP_MPICXX 1
#   include <mpi.h>
```

It forces `ncdfFlow` to compile against `mpi` even though the package doesn't use `parallel` feature at the moment.

It will be nice if we can turn off `parallel` by resetting this flag (i.e. insert `#undef H5_HAVE_PARALLEL`)  But unfortunately we can't modify the `hdf5` headers.

**Comment by mikejiang** [comment]
Following up @jayalmarode's question regarding to `parallel hdf5`, we currently don't need it because [concurrent read](http://www.hdfgroup.org/hdf5-quest.html#gconc1) is already supported by `serial hdf5` which is sufficient for `openCyto`.

**Comment by agartland** [comment]
Hi @mikejiang 
I'm running into an MPI error on the `rhino` servers too. I think its because of the HDF5 libraries in:
`/app/easybuild/software/HDF5/1.8.15-foss-2015b`
which is what `R` is built against.

I tried including `mpi.h` and it seems to work, but when it tries to load `ncdfFlow` it says:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/agartlan/R/x86_64-pc-linux-gnu-library/3.2/ncdfFlow/libs/ncdfFlow.so':
  /home/agartlan/R/x86_64-pc-linux-gnu-library/3.2/ncdfFlow/libs/ncdfFlow.so: undefined symbol: _ZN3MPI8Datatype4FreeEv
```
What is the best way to work around this? (without installing my own version of R and bioconductor)

**Comment by mikejiang** [comment]
Since the `hdf5` is installed in non-standard location, the `prefix` needs to be set in order for it to be linked to `hdf5` library properly. Try this 
```bash
R CMD INSTALL ncdfFlow/ --configure-args="--with-hdf5=/app/hdf5/1.8.13"
```

**Comment by agartland** [comment]
Thanks. The issue was that the `hdf5` build on `rhino` was also built against MPI and I wasn't able to find and build against the same versions thaty `R` was built against. Ultimately I gave up and got everything working on my windows machine. Surprisingly, that was easier!

**Comment by mikejiang** [comment]
Right, there are multiple `hdf5` and `OpenMPI`  instances in `rhinos` which requires a more robust library path detection for `ncdfFlow` package. I will see what I can do with the `configure` script when I have chance.
For now, if you ever want to switch back to the server, the easiest way is to use the serial version of `hdf5` (that I gave previously).

**Comment by ldash** [comment]
@mikejiang what is the correct call devtools `install_github()` to install this package with a non-standard `hdf5` location?

Ok, the answer seems to be this:
`install_github('RGLab/ncdfFlow',ref='trunk',args='--configure-args="--with-hdf5=/app/hdf5/1.8.13"')`
But that errors out for me with the following:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/ldashevs/R/x86_64-pc-linux-gnu-library/3.2/ncdfFlow/libs/ncdfFlow.so':
  libhdf5.so.8: cannot open shared object file: No such file or directory
```

**Comment by mikejiang** [comment]
You need to set `LD_LIBRARY_PATH` for `hdf5` in order for it to be found at runtime

**Comment by ptvan** [comment]
Maybe we should update documentation about this `LD_LIBRARY_PATH` issue ? It got me the last time I installed `ncdfFlow` too, which means others have encountered too, and neither the github installation notes nor bioC page mention it. Might save @mikejiang a few user queries in the future ? :) Just a thought...

**Comment by gfinak** [comment]
This is basic knowledge on how linux finds external libraries for dynamic loading at runtime. It's in the man page for the dynamic linker / loader: http://man7.org/linux/man-pages/man8/ld.so.8.html
