### ISSUE TITLE
fatal error: hdf5.h: No such file or directory

### ISSUE THREAD

**Issue by karelfiser** [RGLab/ncdfFlow#37]
`install_github("RGLab/ncdfFlow")` gives:

`In file included from hdfFlow.c:1:0:
hdfFlow.h:4:18: fatal error: hdf5.h: No such file or directory
 #include "hdf5.h"`

However the hdf5 is installed (Ubuntu) and install_github("RGLab/ncdfFlow") finds it as:
`configure: search for hdf5 library in: /usr/lib`
`configure: found hdf5 library in: /usr/lib`

Also e.g. `biocLite("rhdf5")` installs ok.

Could the hdf5 still be in strange place? Should I try `R CMD INSTALL ncdfFlow_x.y.z.tar.gz --configure-args="--with-hdf5='/path/to'"` ?

Sorry if this is not right place to write and thanks for any pointers.

`session_info()
Session info --------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.441)          
 language en_GB:en                    
 collate  en_GB.UTF-8                 
 tz       <NA>                        

Packages ------------------------------------
 package       * version  date       source        
 BiocInstaller * 1.18.3   2015-06-18 Bioconductor  
 bitops          1.0-6    2013-08-17 CRAN (R 3.0.1)
 curl            0.9      2015-06-19 CRAN (R 3.2.1)
 devtools      * 1.8.0    2015-05-09 CRAN (R 3.2.1)
 digest          0.6.8    2014-12-31 CRAN (R 3.1.2)
 git2r           0.10.1   2015-05-07 CRAN (R 3.2.1)
 httr            1.0.0    2015-06-25 CRAN (R 3.2.1)
 knitr           1.10.5   2015-05-06 CRAN (R 3.2.1)
 magrittr        1.5      2014-11-22 CRAN (R 3.2.0)
 memoise         0.2.1    2014-04-22 CRAN (R 3.2.1)
 Rcpp            0.11.6   2015-05-01 CRAN (R 3.2.1)
 RCurl           1.95-4.7 2015-06-30 CRAN (R 3.2.1)
 rhdf5         * 2.12.0   2015-07-03 Bioconductor  
 rversions       1.0.1    2015-06-06 CRAN (R 3.2.1)
 stringi         0.5-5    2015-06-29 CRAN (R 3.2.1)
 stringr         1.0.0    2015-04-30 CRAN (R 3.2.1)
 xml2            0.1.1    2015-06-02 CRAN (R 3.2.1)
 zlibbioc        1.14.0   2015-06-19 Bioconductor  `

**Comment by gfinak** [comment]
Note that ncdfFlow builds fine on BioConductor. This is an issue on your end, not a bug in the package. 
Have you tried simply installing the binary from the BioConductor site?
Please ask for help on the BioConductor mailing list if you  insist on building from source. 
> Could the hdf5 still be in strange place? 
> Should I try R CMD INSTALL ncdfFlow_x.y.z.tar.gz --configure-args="--with-hdf5='/path/to'" ?
Yes, try downloading the package to your system and installing from the command line with whatever options you need.

**Comment by mikejiang** [comment]
You need to install `hdf5` source as well, try
```bash
apt-get install libhdf5-serial-dev 
```
and `rhdf5` bundles `hdf5` source in the latest version thus it doesn't rely on the external library.

**Comment by karelfiser** [comment]
Hi Mike,

thanks for getting back to that.

I have managed to find correct path to hdf5 and this worked (as per your instructions):  
`R CMD INSTALL ncdfFlow_2.14.0.tar.gz --configure-args="--with-hdf5='/usr/lib/x86_64-linux-gnu/hdf5/serial/'" `

K.
