### ISSUE TITLE
For information only

### ISSUE THREAD

**Issue by SamGG** [RGLab/ncdfFlow#41]
A critical feedback about HDF5
http://cyrille.rossant.net/moving-away-hdf5/

**Comment by gfinak** [comment]
Article is garbage. Their issues are with h5py not HDF5.

**Comment by gfinak** [comment]
I apologize for being dismissive and flippant, but every issue that is opened generates an automatic notification to a number of people in our group. While I appreciate that you are (presumably) trying to be helpful and informative, this is not the right venue for posting links to someone's blog.

**Comment by SamGG** [comment]
I tried to be informative. Sorry for using the wrong way!

**Comment by gfinak** [comment]
If HDF5 is limiting for you in ncdfFlow, I'm happy to hear about it and entertain arguments for an alternative, but there has to be a motivating use case. 

Greg Finak
