### ISSUE TITLE
The channels parameter in read.ncdfFlowSet returns error when supplied with non-NULL arguments

### ISSUE THREAD

**Issue by MiguelRodo** [RGLab/ncdfFlow#45]
Hi Mike

Thanks for writing a great package. 

I ran into an issue when I wanted to explicitly specify which channels `read.ncdfFlowSet` should read in by supplying a character vector to the `channels` argument. It returned the following error: "`chnls_common` not found". This error was not returned when the `channels` argument  was not specified, i.e. left as the default `NULL`.

Examining the source code for `read.ncdfFlowSet`, this appears to happen because the code only  creates the `chnls_common` vector when the `channels` argument is `NULL`. I suggest simply adding in the following code following the `if(is.null(channels))` block:
`else{ chnls_common <- channels }`

I forked the repository and attempted to add this myself, but I got errors when I then attempted to use `read.ncdfFlowSet` after re-building the package (and errors when running the tests). The code seems innocuous enough, so I suspect the fault has to run with not having the right versions of dependencies (though I got no error when building the package) or something hidden like that.

**Comment by mikejiang** [comment]
I added the `else` condition as you did and it works for me. Pull the ` RELEASE_3_9` branch for the fix.

**Comment by MiguelRodo** [comment]
Great, thanks!
