### ISSUE TITLE
Retaining flowFrame Identifiers when Extracting flowFrame from ncdfFlowSet

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/ncdfFlow#46]
Hi @mikejiang,

Do you think it would be possible to maintain the flowFrame identifiers when extracting a flowFrame from an ncdfFlowSet?

```{r}
> class(fs)
[1] "ncdfFlowSet"
attr(,"package")
[1] "ncdfFlow"
> sampleNames(fs)
[1] "Specimen_001_2019-02-06_001_001.fcs"
> identifier(fs[[1]])
[1] "bf233aa5-1f8b-471f-b06c-4424fa11e9fc"
```

Thanks!

Dillon

**Comment by jacobpwagner** [comment]
`identifier` will preferentially return the GUID keyword for the `flowFrame` if it exists (which is what you're running in to with `identifier(fs[[1]])`. That operation differs from the `sampleNames` accessor, which accesses the sample names from the `phenoData` for the `flowSet`.

If the GUID keyword isn't present for a `flowFrame`, then `identifier` will move on to checking the filename keyword. If you would prefer that behavior, you can instead use `keyword(fs[[1]], "FILENAME")` (to get the filename the `flowFrame` was read in from) or `keyword(fs[[1]], "$FIL")` (for the filename keyword actually in the FCS file).

Alternatively, if you just want to use the sample names from the `flowSet` for each individual `flowFrame`, you could just extract them accordingly:
 `sampleNames(fs)[[1]]`
or even manually overwrite the GUID's if they aren't of use:
`identifier(fs)[[1]] <- sampleNames(fs)[[1]]`

**Comment by DillonHammill** [comment]
Is there a reason for the GUID slot change when reading into an ncdfFlowSet?

Would it be possible to return these to their original form in read.ncdfFlowSet?

Alternatively, could we add the option in `identifier()` to access the "FIL" slot?
