### ISSUE TITLE
ncfsApply `ncdfFile` description wrong

### ISSUE THREAD

**Issue by gunthergl** [RGLab/ncdfFlow#48]
Documentation of ncfsApply says parameter 
- `ncdfFile` should be logical wether to create a new hdf file or simply overwrite the existing file.

In fact, the function is just writing to the parameter interpreted as charater.

Apart from that: In the description the function seems to be referenced as "ncdfApply". Should ncfsApply --> ncdfApply or the other way round?

	library(ncdfFlow)
	library(flowCore)
	data(GvHD)
	nc <- ncdfFlowSet(GvHD[1:2])
	ncdfFlow::getFileName(nc) # --> File [TEMPdirectory]/A.nc
	
	#use ncfsApply when FUN returns a flowFrame
	lgcl <- logicleTransform( w = 0.5, t= 10000, m =4.5)
	translist <- transformList(c("FL1-H", "FL2-H"), lgcl)
	nc1 <- ncfsApply(nc, transform, translist)
	ncdfFlow::getFileName(nc) # --> File [TEMPdirectory]/B.nc
	
	
	
	nc2 <- ncfsApply(nc, transform, translist, ncdfFile = TRUE)
	nc3 <- ncfsApply(nc, transform, translist, ncdfFile = FALSE)
	ncdfFlow::getFileName(nc2) # --> File TRUE.nc
	ncdfFlow::getFileName(nc3) # --> File FALSE.nc

	nc4 <- ncfsApply(nc, transform, translist, ncdfFile = "tmpfile.nc")
	ncdfFlow::getFileName(nc3) # --> File tmpfile.nc

**Comment by jacobpwagner** [comment]
@gunthergl , you were right. The doc was not in line with the behavior of `ncdfFile` arg, which is just passed to `clone.ncdfFlowSet` as the path for the new file. Updated the doc to reflect that. And the `ncdfApply` part was a pure typo, so I fixed that as well.
