### ISSUE TITLE
split method for ncdfFlowSet results in crash with isNew=TRUE

### ISSUE THREAD

**Issue by jacobpwagner** [RGLab/ncdfFlow#50]
After merging in the `cytoset` branches, the `split` method for `ncdfFlowSet` taking a `filterResultList` yields a memory error at the C level (invalid free), but only with the `isNew=TRUE` option:

```
library(ncdfFlow)

data("GvHD")
nc1 <- ncdfFlowSet(GvHD)
rGate <- rectangleGate(filterId="rg", "FSC-H"=c(200, 600), "SSC-H"=c(0, 400))
fr <- filter(nc1,rGate)
ncList <- split(nc1,fr, isNew = TRUE)
```

That last line will crash `R`:
```
free(): invalid pointer
Aborted (core dumped)
```
After stepping through in debugging, the issue occurs at line 122 in `ncdfFlowSet-split-methods.R`:
```
if(isNew)
	ncfs<-clone.ncdfFlowSet(ncfs)
```
But `clone.ncdfFlowSet` is not itself broken, as this works fine (and successfully creates the new `cdf` file):
```
library(ncdfFlow)

data("GvHD")
nc1 <- ncdfFlowSet(GvHD)
nc2 <- clone.ncdfFlowSet(nc1)
```
So it must be something about how the logic of the `split` method works after the `cytoset` merge.

**Comment by jacobpwagner** [comment]
Found through the vignette build failing, which is causing the Bioconductor build failures: http://bioconductor.org/checkResults/devel/bioc-LATEST/ncdfFlow/malbec2-buildsrc.html

**Comment by jacobpwagner** [comment]
Just an update for the records, because this is being a bit of a pain to run down. The rough trace of the nested calls:
https://github.com/RGLab/ncdfFlow/blob/cc8ac65cb0043743e1c6cd9395ed2d535613e3aa/R/ncdfFlowSet-split-methods.R#L121-L122
On 406, the RHS `[[` here invoking `readFrame` is the culprit and will cause a crash if called interactively even before this line:
https://github.com/RGLab/ncdfFlow/blob/cc8ac65cb0043743e1c6cd9395ed2d535613e3aa/R/ncdfIO.R#L403-L408
https://github.com/RGLab/ncdfFlow/blob/cc8ac65cb0043743e1c6cd9395ed2d535613e3aa/R/extractFlowFrame.R#L28-L38
In `readFrame.cpp` (via `RcppExports`). The first line here is causing the crash on the second pass through the loop:
https://github.com/RGLab/ncdfFlow/blob/cc8ac65cb0043743e1c6cd9395ed2d535613e3aa/src/readFrame.cpp#L240-L247

This is strange, because all of this code has remained unchanged for quite a while, so it may be worth checking in to the relevant dependencies (`Rcpp`, `Armadillo`). Interestingly, starting from the `bioconductor/devel_base2` docker image and installing all of our relevant packages from GitHub (`RProtoBufLib`, `cytolib`, `flowCore`, `ncdfFlow`), I can't reproduce the crash from the reprex above.

**Comment by jacobpwagner** [comment]
Apparently this issue is also present for extraction applied to a subsetted `ncdfFlowSet`. This will also cause a crash:
```
library(ncdfFlow)

data("GvHD")
nc1<-ncdfFlowSet(GvHD)
rectGate <- rectangleGate(filterId="nonDebris","FSC-H"=c(200,Inf))
fr <- filter(nc1,rectGate)
nc2 <- Subset(nc1, fr)
nc2[[1]]
```

**Comment by mikejiang** [comment]
Indeed, it is hard to pinpoint to the exact cause of the error. likely it is thrown from `R` or `Rcpp` level. Since this chunk of logic (i.e. `subset data by indices using Armadillo c++`) isn't actually used in any of `cytoverse` tool chains (either `release` or `devel`), we may potentially move it to `R` code (just to keep it functioning) instead of keep chasing bugs at `C` level. Especially we now have `cytoset`,`ncdfFlowSet` is to be deprecated anyway.

**Comment by mikejiang** [comment]
I've got rid of the code that cause the bioc build to fail. Just so that this legacy package can continue exist for another release cycle for the sake of legacy GatingSet archive. Again, this error doesn't affect loading/converting legacy gs process.
