### ISSUE TITLE
Slicing

### ISSUE THREAD

**Issue by SamGG** [RGLab/ncdfFlow#52]
Hi,
This is not a bug report, but a question. HDF5 is very efficient for handling big data and slicing the data quicker than SQL. I want to have an efficient management of 100 FCS and slicing them by a cluster identifier that is stored as a channel. I wondering if ncdfFlow is efficient for such slicing.
Best,
Samuel

**Comment by mikejiang** [comment]
ncdfFlow is to be deprecated and won't be actively supported in bioc 3.11. Try to switch to `cytoset` instead. Feel free to elaborate in more details in `flowWorkspace` issue page.
