### ISSUE TITLE
Rstudio crashes with read.ncdfFlowSet()

### ISSUE THREAD

**Issue by abbatidanilo** [RGLab/ncdfFlow#54]
Hello,
Every time I try to load a flowSet with the command read.ncdfFlowSet() RStudio crashes (R session aborted). 
Re-starting Rstudio does not help. Operation attempts were executed on different regular flowSet.
These are the system references:

R.version:
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
...
language       R                           
version.string R version 4.0.5 (2021-03-31)
nickname       Shake and Throw   

Rstudio version is 1.4.1106
Bioconductor version ‘3.12.0’
ncdfFlow version 2.36.0

**Comment by mikejiang** [comment]
ncdfFlowSet is deprecated by cytoset. Try flowWorkspace::load_cytoset_from_fcs() to see if it works.

**Comment by abbatidanilo** [comment]
Hello Mike,
thank you for your reply. 
I always used the normal flowSet in R ver.3. Then I realized that the amount of memory needed was too much (some covid related experiments reported a number of flowFrames > 150!) and so I start replacing the flowSet object with ncdfFlowSet format and it worked.
Then I start migrating to R ver.4 and then the pain started. How can I save the memory in the same way? Is it still possibile to handle big amount of fcs samples with the disk handling as it was before or shall I stick to R ver.3?
thanks

**Comment by mikejiang** [comment]
cytoset is disk-backend as well by default.

**Comment by abbatidanilo** [comment]
Thank you Mike
I will try to use these new cytoframe and cytoset classes... finger crossed 
A part from the https://www.bioconductor.org/packages/release/bioc/vignettes/flowWorkspace/inst/doc/flowWorkspace-Introduction.html. Is there any other valuable documentation available?  
cheers
