### ISSUE TITLE
Compilation errors on macOS

### ISSUE THREAD

**Issue by jacobpwagner** [RGLab/ncdfFlow#55]
Hey @mikejiang and @gfinak. Just a heads up that compilation is getting tripped up for ncdfFlow on MacOS, I think due to the same core reason as https://github.com/RGLab/RProtoBufLib/issues/13, with Clang not supporting C++11 features by default. The errors are actually coming from RcppArmadillo code:

```
*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo
```
and lots of these:
```
error: unknown type name 'constexpr'
```
Here's my current R version and RcppArmadillo version too, just in case that helps:
```
> packageVersion("RcppArmadillo")
[1] ‘0.10.5.0.0’
> R.version.string
[1] "R version 4.1.0 (2021-05-18)"
```
Anyway, the easy solution was the same as for https://github.com/RGLab/RProtoBufLib/issues/13. Adding `CXX_STD = CXX11` to the ncdfFlow Makevars clears it right up.

**Comment by mikejiang** [comment]
Done. Thanks, @jacobpwagner !

**Comment by jacobpwagner** [comment]
Thanks, Mike. It looks good now via `devtools::install_github("RGLab/ncdfFlow")`.
